[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
# Install all dependencies and build the client
buildCommand = "npm install && npm run build"
# Start the server
startCommand = "npm start"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
